---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/centos/centos:8
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
