pipeline{
    agent{
        label 'docker'
    }
    stages{
        stage('checkout git'){
            steps{
                dir('vector-role'){
                    git branch: 'main', credentialsId: 'de9ad2bd-639e-4d01-beaf-8e3267ca2c22', url: 'git@github.com:F1oMaCTeP/vector-role1.git'
                }
            }
        }
        stage('install dependencies'){
            steps{
                dir('vector-role'){
                    sh 'pip3 install -r requirements.txt'
                }
            }
        }
        stage('run molecule'){
            steps{
                dir('vector-role'){
                    sh 'molecule test'
                }
            }
        }
    }
}